### ISSUE TITLE
[Crash] Crash on Starting

### ISSUE THREAD

**Issue by JackNeksa** [timplay33/Create-Mobile-Packages#201]
Using `Registries.CREATIVE_MODE_TAB` causes crash on starting.

**Comment by timplay33** [comment]
This issue should be resolved with the next Hotfix. Could you please confirm that this works?
https://ci.theidler.de/job/Create-Mobile-Packages/job/mc1.20.1%252Fhotfix%252F0.5.4/11/artifact/build/libs/create_mobile_packages-1.20.1-0.5.4-11-mc1.20.1_hotfix_0.5.4.jar

**Comment by timplay33** [comment]
This has been confirmed by a user on Discord. Hotfix is uploading

**Comment by spunchbop121** [comment]
https://gnomebot.dev/paste/mclogs/j0vBUYO
Still happens

**Comment by JackNeksa** [comment]
The newest version of 0.5.4-2 still crashes in my enviroment. Caused by `CreativeModeTabs.SEARCH`.

**Comment by spunchbop121** [comment]
i have the same issue
https://mclo.gs/4pko0dc
